import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex w-full justify-center bg-black">
          <div className="sm:w-[428px] w-full bg-gray-100 min-h-screen relative">
            {children}
            <Navbar />
          </div>
        </div>
      </body>
    </html>
  );
}
